spring:
  application:
    name: SpringWebst
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mjc123
    password: 1234
    url: jdbc:mysql://localhost:3306/mjc8132?useSSL=false&serverTimezone=Asia/Seoul

server:
  port: 18080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  error:
#    whitelabel:
#      enabled: false
#    path: /error

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.nol.springwebst
  configuration:
    map-underscore-to-camel-case: true
